[build]
  command = "docker build -t my-flask-app . && docker run -p 5000:5000 my-flask-app"
  publish = "/"

[dev]
  command = "docker build -t my-flask-app . && docker run -p 5000:5000 my-flask-app"
  port = 5000